nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization','x-auth-token']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization','x-auth-token']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600